### ISSUE TITLE
Maps: download via URL rather than firebase storage

### ISSUE THREAD

**Issue by aNullValue** [junctor/hackertracker-ios#14]
Maps should be downloaded using the URL attribute, and name_text should be used for the name.

I plan to drop: description, file, name, filename.

This is necessary in order to have conference blobs hosted by conference-provided webservers rather than Fiirebase storage.

**Comment by sethlaw** [comment]
Next release (5.3 in the App Store) moves to URL for map retrieval: 226922548b17a389c2056de38834ad095c3ec980.
