### ISSUE TITLE
Merch: Include tax info

### ISSUE THREAD

**Issue by aNullValue** [junctor/hackertracker-ios#17]

**Comment by aNullValue** [comment]
Attribute conference.merch_tax_statement is now available in Firebase for this purpose.

This is a string that will never be null, but may be zero-length.

It **must** be presented at the bottom of pages where prices are indicated (so, product browsing, product detail, and list/total). 

The user may not dismiss this message. 

This message **must** be printed at the bottom of paper lists if price information is printed.

**Comment by sethlaw** [comment]
Done.
