### ISSUE TITLE
Duplicate bookmarks in schedule

### ISSUE THREAD

**Issue by joekir** [junctor/hackertracker-ios#8]
Hi, 

I’ve been looking through the schedule for DC32 and bookmarking talks of interest. But in the schedule view if I filter to bookmarked talks only, every one is shown twice.

Repro:
1. Bookmark a talk
2. Go to schedule view
3. Filter to only bookmarked talks

![IMG_3261](https://github.com/user-attachments/assets/d29aae82-e87e-49d5-8c95-065cbaf93483)

**Comment by sethlaw** [comment]
Thanks @joekir. Working through some new updates and the backend data updates are causing some residual issues. Let me know if your willing to join Testflight to see if updates solve the issue.

**Comment by joekir** [comment]
Hi @sethlaw,

Thanks for the quick fix, I saw a new update just landed and duplicates are gone now
 
![image](https://github.com/user-attachments/assets/f1a5c244-4149-477f-9f82-af0e0048585d)
